#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#define PRINTF_DISABLE_SUPPORT_FLOAT
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 0
/* 32 对嵌入式 int 打印过剩，略减可省 printf 内栈与少量代码 */
#define PRINTF_NTOA_BUFFER_SIZE 16U

